version: '3.9'

services:

    database:
        container_name: database
        image: postgres:alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: $DB_NAME
            POSTGRES_USER: $DB_USER
            POSTGRES_PASSWORD: $DB_PASSWORD
        volumes:
            - ./test-database.sql:/docker-entrypoint-initdb.d/test-database.sql